trigger: none

pool: powermanage-pool

# =================================
# PARAMETERS
# =================================
parameters:
  - name: environment
    displayName: select environment
    type: string
    default: dev
    values:
      - dev
      - qa
      - prod

  - name: approver
    displayName: Approver email
    type: string
    default: 'mohitchauhan.qa@gmail.com'

# =================================
# variables
# =================================
variables:
  serviceconnection: 'connection_service'
  terraformworkingdir: '$(System.DefaultWorkingDirectory)/todoappinfra'
  subscriptionid: '561ee10c-91f3-420a-b686-4bb845074d5c'
  resourceGroupName: 'rg-terraformstorage123'
  storageAccountName: 'stgterraform1426'
  containerName: 'mycontainer1234'
  tfStateKey: '${{ parameters.environment }}.tfstate'
  approverEmail: 'mohitchauhan.qa@gmail.com'

stages:

#=================================
# Stage - 1 Setup
#=================================

- stage: Setup
  displayName: "Terraform Install"

  jobs:
    - job: InstallTerraform

      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

#=================================
# Stage - 2 Validation & init
#=================================
- stage: Validation
  displayName: "Terraform Validation & init"
  dependsOn: Setup

  jobs:
    - job: validateTerraform

      steps:
      
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform format check
        inputs:
          provider: 'azurerm'
          command: 'custom'
          workingDirectory: '$(terraformworkingdir)'
          outputTo: 'console'
          customCommand: 'fmt'
          environmentServiceNameAzureRM: '$(serviceconnection)'
          environmentAzureRmOverrideSubscriptionID: '$(subscriptionid)'

      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformworkingdir)'
          backendServiceArm: '$(serviceconnection)'
          backendAzureRmOverrideSubscriptionID: '$(subscriptionid)'
          backendAzureRmResourceGroupName: '$(resourceGroupName)'
          backendAzureRmStorageAccountName: '$(storageAccountName)'
          backendAzureRmContainerName: '$(containerName)'
          backendAzureRmKey: '$(tfStateKey)'

      - task: TerraformTask@5
        displayName: Terraform validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(terraformworkingdir)'

#===================Security===========================================================

- stage: Terraform_Lint
  displayName: Terraform Lint
  dependsOn: Validation

  jobs:
  - job: Run_TFLint
    displayName: Run TFLint

    steps:
    - script: |
        tflint --init
      workingDirectory: $(default)
      displayName: Initialize TFLint

    - script: |
        tflint
      workingDirectory: $(default)
      displayName: Run TFLint

- stage: Terraform_Security
  displayName: Terraform Security Scan
  dependsOn: Terraform_Lint

  jobs:
  - job: Run_tfsec
    displayName: Run tfsec Security Scan

    steps:
    - script: |
        tfsec .
      displayName: Run tfsec

#=================================
# Stage - 3 Plan
#=================================
- stage: Plan
  displayName: Terraform plan
  dependsOn: Terraform_Security

  jobs:
    - job: Terraformplan

      steps:
      
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformworkingdir)'
          backendServiceArm: '$(serviceconnection)'
          backendAzureRmOverrideSubscriptionID: '$(subscriptionid)'
          backendAzureRmResourceGroupName: '$(resourceGroupName)'
          backendAzureRmStorageAccountName: '$(storageAccountName)'
          backendAzureRmContainerName: '$(containerName)'
          backendAzureRmKey: '$(tfStateKey)'

      - task: TerraformTask@5
        displayName: Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(terraformworkingdir)'
          environmentServiceNameAzureRM: '$(serviceconnection)'
          environmentAzureRmOverrideSubscriptionID: '$(subscriptionid)'

#=================================
# Stage - 4 Maual Validation     
#=================================

- stage: Approval
  displayName: Manual Validation
  dependsOn: Plan

  jobs:
    - job: waitforApproval
      pool: server

      steps:
      
      - task: ManualValidation@1
        timeoutInMinutes: 60
        inputs:
          notifyUsers: '${{ parameters.approver }}'
          approvers: '${{ parameters.approver }}'
          instructions: 'Approve deployment for ${{ parameters.environment }} environment'
          onTimeout: reject

#=================================
# Stage - 5 Apply 
#=================================
- stage: Apply
  displayName: Terraform Apply
  dependsOn:  Approval

  jobs:
    - job: TerraformApply

      steps:
      
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformworkingdir)'
          backendServiceArm: '$(serviceconnection)'
          backendAzureRmOverrideSubscriptionID: '$(subscriptionid)'
          backendAzureRmResourceGroupName: '$(resourceGroupName)'
          backendAzureRmStorageAccountName: '$(storageAccountName)'
          backendAzureRmContainerName: '$(containerName)'
          backendAzureRmKey: '$(tfStateKey)'

      - task: TerraformTask@5
        displayName: terraformapply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(terraformworkingdir)'
          environmentServiceNameAzureRM: '$(serviceconnection)'
          environmentAzureRmOverrideSubscriptionID: '$(subscriptionid)'
