trigger: none

pool: powermanage-pool

stages:

#=================================
# Stage - 1 Setup
#=================================

- stage: Setup
  displayName: "Terraform Install"

  jobs:
    - job: InstallTerraform

      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

#=================================
# Stage - 2 Validation & init
#=================================
- stage: Validation
  displayName: "Terraform Validation & init"
  dependsOn: Setup

  jobs:
    - job: validateTerraform

      steps:
      
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform format check
        inputs:
          provider: 'azurerm'
          command: 'custom'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
          outputTo: 'console'
          customCommand: 'fmt'
          environmentServiceNameAzureRM: 'my_service_connection_pat'
          environmentAzureRmOverrideSubscriptionID: '69ba3bc7-f967-4749-bbe8-54cb06e4a54a'

      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
          backendServiceArm: 'my_service_connection_pat'
          backendAzureRmOverrideSubscriptionID: '69ba3bc7-f967-4749-bbe8-54cb06e4a54a'
          backendAzureRmResourceGroupName: 'container_rg'
          backendAzureRmStorageAccountName: 'statefilestg12'
          backendAzureRmContainerName: 'mohitcontainer12'
          backendAzureRmKey: 'patronics_terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'

#=================================
# Stage - 3 Plan
#=================================
- stage: Plan
  displayName: Terraform plan
  dependsOn: Validation

  jobs:
    - job: Terraformplan

      steps:
      
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
          backendServiceArm: 'my_service_connection_pat'
          backendAzureRmOverrideSubscriptionID: '69ba3bc7-f967-4749-bbe8-54cb06e4a54a'
          backendAzureRmResourceGroupName: 'container_rg'
          backendAzureRmStorageAccountName: 'statefilestg12'
          backendAzureRmContainerName: 'mohitcontainer12'
          backendAzureRmKey: 'patronics_terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
          environmentServiceNameAzureRM: 'my_service_connection_pat'
          environmentAzureRmOverrideSubscriptionID: '69ba3bc7-f967-4749-bbe8-54cb06e4a54a'

#=================================
# Stage - 4 Maual Validation     
#=================================

- stage: Approval
  displayName: Manual Validation
  dependsOn: Plan

  jobs:
    - job: waitforApproval
      pool: server

      steps:
      
      - task: ManualValidation@1
        timeoutInMinutes: 60
        inputs:
          notifyUsers: 'mohitchauhan.qa@gmail.com'
          approvers: 'mohitchauhan.qa@gmail.com'
          instructions: 'aprrove my code'
          onTimeout: reject

#=================================
# Stage - 5 Apply 
#=================================
- stage: Apply
  displayName: Terraform Apply
  dependsOn:  Approval

  jobs:
    - job: TerraformApply

      steps:
      
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
          backendServiceArm: 'my_service_connection_pat'
          backendAzureRmOverrideSubscriptionID: '69ba3bc7-f967-4749-bbe8-54cb06e4a54a'
          backendAzureRmResourceGroupName: 'container_rg'
          backendAzureRmStorageAccountName: 'statefilestg12'
          backendAzureRmContainerName: 'mohitcontainer12'
          backendAzureRmKey: 'patronics_terraform.tfstate'

      - task: TerraformTask@5
        displayName: terraformapply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
          environmentServiceNameAzureRM: 'my_service_connection_pat'
          environmentAzureRmOverrideSubscriptionID: '69ba3bc7-f967-4749-bbe8-54cb06e4a54a'
