trigger: none

pool: powermanage-pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'my_service_connection_pat'
    backendAzureRmOverrideSubscriptionID: '69ba3bc7-f967-4749-bbe8-54cb06e4a54a'
    backendAzureRmResourceGroupName: 'container_rg'
    backendAzureRmStorageAccountName: 'statefilestg12'
    backendAzureRmContainerName: 'mohitcontainer12'
    backendAzureRmKey: 'patronics_terraform.tfstate'